name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn test:unit
